### ISSUE TITLE
华为荣耀6x ，在选择图片的时候,点击图片闪退。

### ISSUE THREAD

**Issue by WencaiHwcazy** [bingoogolapple/BGAPhotoPicker-Android#101]
华为荣耀6x ，在选择图片的时候,点击图片闪退。

**Comment by WencaiHwcazy** [comment]
java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1546)
	at android.app.Activity.startActivityForResult(Activity.java:4391)
	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
	at android.app.Activity.startActivityForResult(Activity.java:4335)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
	at cn.bingoogolapple.photopicker.activity.BGAPhotoPickerActivity.changeToPreview(BGAPhotoPickerActivity.java:381)
	at cn.bingoogolapple.photopicker.activity.BGAPhotoPickerActivity.onItemChildClick(BGAPhotoPickerActivity.java:340)
	at cn.bingoogolapple.androidcommon.adapter.BGAViewHolderHelper$1.onNoDoubleClick(BGAViewHolderHelper.java:115)
	at cn.bingoogolapple.androidcommon.adapter.BGAOnNoDoubleClickListener.onClick(BGAOnNoDoubleClickListener.java:42)
	at android.view.View.performClick(View.java:5646)
	at android.view.View$PerformClick.run(View.java:22459)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
Caused by: android.os.TransactionTooLargeException: data parcel size 1148952 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:617)
	at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3089)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1539)
	... 18 more
android.os.TransactionTooLargeException: data parcel size 1148952 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:617)
	at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3089)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1539)
	at android.app.Activity.startActivityForResult(Activity.java:4391)
	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
	at android.app.Activity.startActivityForResult(Activity.java:4335)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
	at cn.bingoogolapple.photopicker.activity.BGAPhotoPickerActivity.changeToPreview(BGAPhotoPickerActivity.java:381)
	at cn.bingoogolapple.photopicker.activity.BGAPhotoPickerActivity.onItemChildClick(BGAPhotoPickerActivity.java:340)
	at cn.bingoogolapple.androidcommon.adapter.BGAViewHolderHelper$1.onNoDoubleClick(BGAViewHolderHelper.java:115)
	at cn.bingoogolapple.androidcommon.adapter.BGAOnNoDoubleClickListener.onClick(BGAOnNoDoubleClickListener.java:42)
	at android.view.View.performClick(View.java:5646)
	at android.view.View$PerformClick.run(View.java:22459)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by ArcherLucky** [comment]
顶一下
