### ISSUE TITLE
.NoSuchMethodError，我用的glide4.0.0，需要升级么？

### ISSUE THREAD

**Issue by ITzhangyan** [bingoogolapple/BGAPhotoPicker-Android#131]
java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/RequestBuilder; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.EdLab-1/base.apk)
                                                               at cn.bingoogolapple.photopicker.imageloader.BGAGlideImageLoader.display(BGAGlideImageLoader.java:47)
                                                               at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:76)
                                                               at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:83)
                                                               at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:87)
                                                               at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:91)
                                                               at cn.bingoogolapple.photopicker.widget.BGASortableNinePhotoLayout$PhotoAdapter.fillData(BGASortableNinePhotoLayout.java:466)
                                                               at cn.bingoogolapple.photopicker.widget.BGASortableNinePhotoLayout$PhotoAdapter.fillData(BGASortableNinePhotoLayout.java:411)
                                                               at cn.bingoogolapple.baseadapter.BGARecyclerViewAdapter.onBindViewHolder(BGARecyclerViewAdapter.java:102)
                                                               at cn.bingoogolapple.baseadapter.BGARecyclerViewAdapter.onBindViewHolder(BGARecyclerViewAdapter.java:32)
                                                               at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                               at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                               at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                               at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                               at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                               at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                               at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                               at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                               at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                               at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                               at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                               at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                               at android.view.View.layout(View.java:17658)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5615)
                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                               at android.view.View.layout(View.java:17658)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5615)
                                                               at android.support.v7.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:8839)
                                                               at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1609)
                                                               at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                               at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                               at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                               at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
                                                               at android.view.View.measure(View.java:19878)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6132)
                                                               at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                               at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                               at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                               at android.view.View.measure(View.java:19878)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6132)
                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
04-16 17:24:58.980 29809-29809/com.EdLab E/AndroidRuntime:     at android.view.View.measure(View.java:19878)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6132)
                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                               at android.view.View.measure(View.java:19878)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6132)
                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                               at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                               at android.view.View.measure(View.java:19878)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6132)
                                                               at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                               at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                               at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                               at android.view.View.measure(View.java:19878)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6132)
                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                               at android.view.View.measure(View.java:19878)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6132)
                                                               at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                               at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                               at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                               at android.view.View.measure(View.java:19878)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6132)
                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                               at com.android.internal.policy.DecorView.onMeasure(DecorView.java:855)
                                                               at android.view.View.measure(View.java:19878)
                                                               at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2543)
                                                               at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1618)
                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1882)
                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1494)
                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6953)
                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:883)
                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:689)
                                                               at android.view.Choreographer.doFrame(Choreographer.java:624)
                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:869)
                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:159)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6326)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

**Comment by 5en** [comment]
i also get this touble

**Comment by 5en** [comment]
i solve it use glide   compile 'com.github.bumptech.glide:glide:4.7.1'

**Comment by rex26** [comment]
> i solve it use glide compile 'com.github.bumptech.glide:glide:4.7.1'

the aar and docs is dismatch,it took me a half day ..........................................

**Comment by huyongqiang** [comment]
改成glide4.7.1没用啊 @5en

**Comment by huyongqiang** [comment]
解决方法还是和兼容glide3一样的[兼容Glide3](https://github.com/bingoogolapple/BGAPhotoPicker-Android/issues/118)，添加一个public class BGAGlideImageLoader4 extends BGAImageLoader{...}即可。
