### ISSUE TITLE
选择图片时候查看大图奔溃

### ISSUE THREAD

**Issue by gypnick** [bingoogolapple/BGAPhotoPicker-Android#136]
使用的是 glide3.7.0     
java.lang.IllegalAccessError: Method 'int uk.co.senab.photoview.PhotoViewAttacher.getImageViewWidth(android.widget.ImageView)' is inaccessible to class 'cn.bingoogolapple.photopicker.util.BGABrowserPhotoViewAttacher' (declaration of 'cn.bingoogolapple.photopicker.util.BGABrowserPhotoViewAttacher' appears in /data/app/com.iwisedev.tourismLive-1/split_lib_dependencies_apk.apk:classes2.dex)
                      at cn.bingoogolapple.photopicker.util.BGABrowserPhotoViewAttacher.setTopCrop(BGABrowserPhotoViewAttacher.java:66)
                      at cn.bingoogolapple.photopicker.util.BGABrowserPhotoViewAttacher.updateBaseMatrix(BGABrowserPhotoViewAttacher.java:45)
                      at cn.bingoogolapple.photopicker.util.BGABrowserPhotoViewAttacher.setUpdateBaseMatrix(BGABrowserPhotoViewAttacher.java:58)
                      at cn.bingoogolapple.photopicker.adapter.BGAPhotoPageAdapter$1.onDrawableChanged(BGAPhotoPageAdapter.java:62)
                      at cn.bingoogolapple.photopicker.widget.BGAImageView.notifyDrawableChanged(BGAImageView.java:158)
                      at cn.bingoogolapple.photopicker.widget.BGAImageView.setImageDrawable(BGAImageView.java:134)
                      at com.bumptech.glide.request.target.GlideDrawableImageViewTarget.setResource(GlideDrawableImageViewTarget.java:80)
                      at com.bumptech.glide.request.target.GlideDrawableImageViewTarget.setResource(GlideDrawableImageViewTarget.java:12)
                      at com.bumptech.glide.request.target.ImageViewTarget.onResourceReady(ImageViewTarget.java:76)
                      at com.bumptech.glide.request.target.GlideDrawableImageViewTarget.onResourceReady(GlideDrawableImageViewTarget.java:66)
                      at com.bumptech.glide.request.target.GlideDrawableImageViewTarget.onResourceReady(GlideDrawableImageViewTarget.java:12)
                      at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:525)
                      at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:507)
                      at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:158)
                      at com.bumptech.glide.load.engine.EngineJob.access$100(EngineJob.java:22)
                      at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:202)
                      at android.os.Handler.dispatchMessage(Handler.java:101)
                      at android.os.Looper.loop(Looper.java:156)
                      at android.app.ActivityThread.main(ActivityThread.java:6595)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by BrightnessYin** [comment]
请问您解决了吗？，我目前也出现了这个问题

**Comment by lindroy** [comment]
> 
> 
> 请问您解决了吗？，我目前也出现了这个问题

除非把源码下下来自己缩小图片，或者用知乎的Matisse.
