### ISSUE TITLE
  java.lang.NoSuchMethodError: No virtual method placeholder(I)Lcom/bumptech/glide/request/RequestOptions; i

### ISSUE THREAD

**Issue by lbx2015** [bingoogolapple/BGAPhotoPicker-Android#169]
I am using in my project like following:
    implementation 'pub.devrel:easypermissions:1.0.1'
    implementation 'cn.bingoogolapple:bga-qrcode-zxing:1.3.6'
    implementation 'cn.bingoogolapple:bga-photopicker:1.2.8@aar'
    implementation 'cn.bingoogolapple:bga-baseadapter:1.2.9@aar'
    implementation 'cn.bingoogolapple:bga-flowlayout:1.0.0@aar'

    //adding glide library
    implementation 'com.github.bumptech.glide:glide:4.9.0'
    implementation "com.github.bumptech.glide:okhttp3-integration:4.9.0"
    annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'

and got the error on click pick images
java.lang.NoSuchMethodError: No virtual method placeholder(I)Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/com.heitouyang.promise-YeiJseHQAyAnf7sIQSKFyw==/base.apk)
        at cn.bingoogolapple.photopicker.imageloader.BGAGlideImageLoader.display(BGAGlideImageLoader.java:47)
        at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:76)
        at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:83)
        at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:87)
        at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:91)
        at cn.bingoogolapple.photopicker.adapter.BGAPhotoPickerAdapter.fillData(BGAPhotoPickerAdapter.java:66)
        at cn.bingoogolapple.photopicker.adapter.BGAPhotoPickerAdapter.fillData(BGAPhotoPickerAdapter.java:34)
        at cn.bingoogolapple.baseadapter.BGARecyclerViewAdapter.onBindViewHolder(BGARecyclerViewAdapter.java:102)
        at cn.bingoogolapple.baseadapter.BGARecyclerViewAdapter.onBindViewHolder(BGARecyclerViewAdapter.java:32)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)

**Comment by zjxuzhj** [comment]
一样的问题

**Comment by zjxuzhj** [comment]
#118 最下边兼容glide4.9
