### ISSUE TITLE
android 10 添加图片后逐个删除会报错

### ISSUE THREAD

**Issue by chensong1993** [bingoogolapple/BGAPhotoPicker-Android#186]
java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
        at java.util.ArrayList.get(ArrayList.java:439)
        at cn.bingoogolapple.baseadapter.BGARecyclerViewAdapter.getItem(BGARecyclerViewAdapter.java:181)
        at cn.bingoogolapple.photopicker.widget.BGASortableNinePhotoLayout$PhotoAdapter.getItem(BGASortableNinePhotoLayout.java:439)
        at cn.bingoogolapple.photopicker.widget.BGASortableNinePhotoLayout.onItemChildClick(BGASortableNinePhotoLayout.java:371)
        at cn.bingoogolapple.baseadapter.BGAViewHolderHelper$1.onNoDoubleClick(BGAViewHolderHelper.java:115)
        at cn.bingoogolapple.baseadapter.BGAOnNoDoubleClickListener.onClick(BGAOnNoDoubleClickListener.java:42)

**Comment by BaiMingxu1** [comment]
您好，请问您解决了么？
