### ISSUE TITLE
依赖放本地报错

### ISSUE THREAD

**Issue by zhaichuankai** [bingoogolapple/BGAPhotoPicker-Android#197]
java.lang.NoClassDefFoundError: Failed resolution of: Lcn/bingoogolapple/photopicker/activity/BGAPhotoPickerActivity;
        at cn.bingoogolapple.photopicker.activity.BGAPhotoPickerActivity$IntentBuilder.<init>(BGAPhotoPickerActivity.java:122)
        at com.boniu.paizhaoshiwu.appui.activity.TakePhotoActivity$1.onDeblockingClick(TakePhotoActivity.java:43)
        at com.boniu.paizhaoshiwu.widget.DeblockingDialog$1.onClick(DeblockingDialog.java:42)

**Comment by zhaichuankai** [comment]
远程依赖没问题
