### ISSUE TITLE
报错的问题，很多人都有

### ISSUE THREAD

**Issue by aesion** [bingoogolapple/BGAPhotoPicker-Android#71]
Process: cn.bingoogolapple.photopicker.demo, PID: 29317
    java.lang.ClassCastException: android.support.v7.widget.TintContextWrapper cannot be cast to android.app.Activity
            at cn.bingoogolapple.photopicker.imageloader.BGAGlideImageLoader.display(BGAGlideImageLoader.java:43)
            at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:64)
            at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:68)
            at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:72)
            at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:76)
            at cn.bingoogolapple.photopicker.widget.BGANinePhotoLayout.setData(BGANinePhotoLayout.java:170)
            at cn.bingoogolapple.photopicker.demo.activity.MomentListActivity$MomentAdapter.fillData(MomentListActivity.java:201)
            at cn.bingoogolapple.photopicker.demo.activity.MomentListActivity$MomentAdapter.fillData(MomentListActivity.java:184)

**Comment by bingoogolapple** [comment]
麻烦加下QQ 496312716

**Comment by aesion** [comment]
compile 'cn.bingoogolapple:bga-photopicker:1.2.2@aar'
这个1.2.1改成1.2.2就可以了，谢大神
