### ISSUE TITLE
4.1系统上的异常

### ISSUE THREAD

**Issue by WanLiLi** [bingoogolapple/BGAPhotoPicker-Android#73]
java.lang.ClassCastException: android.support.v7.widget.TintContextWrapper cannot be cast to android.app.Activity
                                                                                        at cn.bingoogolapple.photopicker.imageloader.BGAGlideImageLoader.display(BGAGlideImageLoader.java:43)
                                                                                        at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:64)
                                                                                        at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:68)
                                                                                        at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:72)
                                                                                        at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:76)
                                                                                        at cn.bingoogolapple.photopicker.widget.BGANinePhotoLayout.setData(BGANinePhotoLayout.java:170)
                                                                                        at cn.bingoogolapple.photopicker.demo.activity.MomentListActivity$MomentAdapter.fillData(MomentListActivity.java:200)
                                                                                        at cn.bingoogolapple.photopicker.demo.activity.MomentListActivity$MomentAdapter.fillData(MomentListActivity.java:183)

**Comment by bingoogolapple** [comment]
已修复，请使用最新版 1.2.2

**Comment by WanLiLi** [comment]
神速啊，可否简单说一下什么原因吗

**Comment by bingoogolapple** [comment]
去看最新那个 commit 吧
